services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
